name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APT_PARAMS: 'sudo apt -y -qq -o=Dpkg::Use-Pty=0'
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Cleanup Storage
        run: |
          sudo docker image prune --all --force
          sudo systemctl stop docker || true
          sudo systemctl disable docker || true
          docker system prune -a -f --volumes || true
          $APT_PARAMS autoremove --purge -y nodejs npm yarn snapd runc docker-ce docker-ce-cli containerd.io docker-compose-plugin \
            'postgresql*' 'mysql*' redis* ghc* llvm* powershell mono* azure-cli google-cloud-sdk openjdk* firefox \
            dotnet* mongodb* 'php*' 'ruby*' 'gdb*' 'libllvm*' 'clang*' 'libvulkan*' 'aspnetcore-*' 'swift*' 'libcublas*' 'libcuda*' 'cuda*' 'x11-*' 'google-chrome-stable' gcc-aarch64-linux-gnu+ g++-aarch64-linux-gnu+
          $APT_PARAMS autoremove --purge -y
          $APT_PARAMS autoclean
          $APT_PARAMS clean
          sudo rm -rf /var/lib/docker /var/lib/containerd /etc/docker /usr/bin/docker* \
            /usr/bin/containerd* /usr/bin/runc /run/docker /var/run/docker.sock /var/log/docker* /usr/share/dotnet /usr/local/.ghcup /opt/hostedtoolcache/ /usr/local/share/powershell /usr/local/share/chromium /opt /usr/share/swift /opt/ghc /usr/local/lib/android /usr/local/lib/python*/dist-packages /usr/local/lib/python*/site-packages \
            /usr/local/lib/python*/__pycache__ ~/.cache/pip /usr/local/lib/python3*/dist-packages/* \
            ~/.npm ~/.cache /usr/local/lib/ruby/gems/* /var/lib/apt/lists/* /var/cache/apt/archives/* /var/log/* /tmp/* \
            /usr/share/man /usr/share/doc /usr/share/locale $ANDROID_HOME/..
          df -ha

      - name: Get Repo
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          sudo mv repo /usr/local/bin
          sudo chmod a+rx /usr/local/bin/repo

      - name: Get llvm-toolchain
        run: |
          repo init -u https://android.googlesource.com/platform/manifest -b llvm-toolchain
          repo sync -c

      - name: Build llvm-toolchain
        run: python toolchain/llvm_android/build.py --skip-tests --lto --no-build windows
