name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Cleanup Storage
        run: |
          # Stop and remove Docker services
          sudo systemctl stop docker || true
          sudo systemctl disable docker || true
          docker system prune -a -f --volumes || true

          # Remove Docker packages and dependencies
          sudo apt-get autoremove --purge -y docker-ce docker-ce-cli containerd.io docker-compose-plugin \
            'postgresql*' 'mysql*' 'manpages*' 'ruby*' 'gdb*' 'llvm*' 'perl*' 'libllvm*' 'clang*' 'libcuda*' \
            'libvulkan*' 'swift*' 'mono*' 'azure*' 'ghc*' 'dotnet*' 'firefox' 'libcublas*' 'cuda*' 'x11-*'
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          sudo apt-get clean -y

          # Remove Docker-related directories and binaries
          sudo rm -rf /var/lib/docker /var/lib/containerd /etc/docker /usr/bin/docker* \
            /usr/bin/containerd* /usr/bin/runc /run/docker /var/run/docker.sock /var/log/docker*

          # Remove other unnecessary files and directories
          sudo rm -rf /usr/local/lib/python*/dist-packages /usr/local/lib/python*/site-packages \
            /usr/local/lib/python*/__pycache__ ~/.cache/pip /usr/local/lib/python3*/dist-packages/* \
            /usr/share/dotnet /usr/local/lib/android /opt/ghc $AGENT_TOOLSDIRECTORY/* ~/.npm \
            ~/.cache /usr/local/lib/node_modules /usr/local/lib/ruby/gems/* /var/log/* /tmp/* \
            /usr/share/man /usr/share/doc /usr/share/locale $ANDROID_HOME/..

          # Output free disk space to verify
          df -ha

      - name: Get Dependencies
        run: |
          sudo apt update
          # sudo apt upgrade -y
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          sudo mv repo /usr/local/bin
          sudo chmod a+rx /usr/local/bin/repo

      - name: Get llvm-toolchain
        run: |
          repo init -u https://android.googlesource.com/platform/manifest -b llvm-toolchain
          repo sync -c

      - name: Build llvm-toolchain
        run: python toolchain/llvm_android/build.py --skip-tests --lto --no-build windows
